insert into `category` values
(1, 'Văn Học Việt Nam'),
(2, 'Văn Học Nước Ngoài'),
(3, 'Thiếu Nhi'),
(4, 'Thời Sự - Chính Trị');


INSERT INTO `book`  VALUES 
(1, 'Nguyễn Văn Nghĩa', 'MS001', 'Hẹn nhau phía sau tan vỡ là một cuốn tản văn nhẹ nhàng, dành cho những trái tim vẫn đang ôm vết thương tình cảm, chữa mãi không lành. Cuốn sách mang một nỗi buồn man mác, dịu nhẹ khiến bạn dường như thấy câu chuyện của mình đang hiện lên trong từng trang sách. Đây tựa như là một cuốn nhật ký của chính bạn, ghi lại những kỷ niệm đã cũ về người cũ với biết bao chữ “đã từng”: đã từng là ngoại lệ của nhau, đã từng bỏ lỡ nhau, đã từng trao toàn bộ trái tim và hứa sẽ không xa rời,…', '10', 10.1, 'https://i.pinimg.com/564x/4b/23/a8/4b23a8b278a13ffda37850d9e4d6f0dc.jpg', 'Hẹn nhau bên gốc đa...', 2000, 'NXB Kim Đồng', 100, '2020-09-01', 0, 20, 'Lưu Hòa', 3),
(2, 'Lương Bích Hữu', 'MS002', 'Giá trị thật sự của cuộc sống là sự bình yên trong tâm hồn. Chúng ta vẫn hay xem bình yên chỉ là những khoảnh khắc ít ỏi trong cuộc đời của mỗi người. Khi những khoảnh khắc ấy trôi qua thì mọi người đều phải trở về nhịp sống hối hả như một thói quen thường nhật. Nếu mang trong mình những suy nghĩ và lối sống như vậy thì cuốn sách “Tôi không thích ồn ào” sẽ giúp bạn có thêm những góc nhìn mới về sự bình yên (định nghĩa lại khái niệm về bình yên)', '10', 11.1, 'https://sach86.com/wp-content/uploads/2019/12/toi-khong-thich-on-ao.jpg', 'Tôi không thích ồn ào.', 2000, 'NXB Kim Đồng', 100, '2020-09-01', 0, 20, 'Nguyễn Thành Long', 1),
(3, 'Nguyễn Văn Minh', 'MS003', '“Một số người coi tình cũ như vết thương, một số khác coi như chiến tích, số khác nữa lại coi như nỗi ân hận suốt đời.Còn tôi không có tình cũ, vì càng giữ nó càng mới!“Tình cũ” luôn là một thứ gì đó án ngữ trong tim, mà mỗi lần nhớ về lòng ta lại chua xót. Không phải là còn yêu, cũng không phải là hận, để mà không muốn nhận danh xưng Người-Yêu-Cũ, chỉ đơn giản, những thứ cũ kỹ luôn đi cùng cảm giác nuối tiếc buồn thương, mà có ai lại muốn chấp nhận việc trong cuộc đời một người, mình chỉ là kẻ giữ chỗ cho người mới đến sau…', '10', 11.1, 'https://www.dtv-ebook.com/images/files_2/2019/dung-goi-anh-la-nguoi-yeu-cu-du-phong.jpg', 'Đừng gọi anh là người...', 1000, 'NXB Kim Đồng', 100, '2019-09-01', 0, 20, 'Nguyễn Thành Nhân', 3),
(4, 'Diệp lạc vô tâm', 'MS004', 'Yêu là thế giống như một cuốn tự truyện, một cuốn nhật ký miêu tả rất sinh động cuộc đời 10 năm của tác giả, từ cô nữ sinh mập mạp, ngốc nghếch, ngây thơ phấn đấu trở thành sinh viên đại học nổi tiếng, thầm thương trộm nhớ một chàng trai cùng trường thông minh, giỏi giang kém mình 2 tuổi.', '10', 11.1, 'https://downloadsach.com/wp-content/uploads/2018/01/sach-yeu-la-the.jpg', 'Yêu là thế', 2000, 'NXB Văn Học', 100, '2018-09-01', 0, 20, 'Diệp lạc vô tâm', 2),
(5, 'Antoine de Saint-Exupéry', 'MS005', '“Hoàng tử bé” – tựa gốc “Le Petit Prince” – là một truyện ngắn của viên phi công có biệt danh thân mật trong phi hành đoàn là “thiếu tá Saint-Ex”, cuốn sách ra mắt năm 1943, từ đó làm say mê hàng triệu độc giả trên toàn thế giới.Tại ngôi nhà The Bevin House ở Long Island, New York, Saint-Ex đã ngày đêm viết và vẽ minh họa cho “Hoàng tử bé”, với sự trợ giúp của bánh kẹp trứng trộn, gin, tonic, coca cola và thuốc lá.Cho đến nay, tác phẩm đã được dịch sang 257 ngôn ngữ (theo Le Parisien) và đã bán được hơn 200 triệu bản, trở thành một trong những cuốn sách bán chạy nhất mọi thời đại. Truyện còn được dùng như tài liệu học ngoại ngữ cho người mới bắt đầu.', '10', 11.1, 'https://product.hstatic.net/200000343865/product/hoang-tu-be---tb-2022_f0f2f9b813c246c4878e7e685f683d50_master.jpg', 'Hoàng tử bé', 2000, 'NXB Kim Đồng', 100, '2020-09-01', 0, 20, 'Nguyễn Văn Trung', 4),
(6, 'Hoàng Anh Tuấn', 'MS006', 'Lớp học mật ngữ là một bộ truyện đặc biệt về cung Hoàng đạo, bật mí những bí mật thưở còn thò lò mũi xanh của 12 cung Hoàng đạo. Bạn là một Bạch Dương trẻ con nhưng nhiệt tình với bạn bè, hay là một Kim Ngưu có “tình yêu bất diệt” với… đồ ăn? Hay thậm chí là một cô nàng Thiên Yết lạnh lùng, khó hiểu nhưng nội tâm cực kì?', '10', 11.9, 'https://salt.tikicdn.com/cache/w1200/ts/product/c2/22/a7/c11e314e0900d12eda3c5b2b60e9bdee.jpg', 'Lớp học mật ngữ', 2000, 'NXB Kim Đồng', 100, '2022-09-01', 0, 20, 'Hoàng Anh Tuấn', 2),
(7, 'Nguyễn Văn Nghĩa', 'MS007', 'Đầu tiên mình xin đính chính là “Bệnh không thể yêu” ở đây không phải là bệnh mà chị em sắc nữ nghĩ đâu, nói anh nam chính thành bất lực thì oan cho anh quá rồi. Chỉ là anh ấy 29 tuổi đầu vẫn độc thân không mảnh tình vắt vai và cực kì không muốn yêu ai thôi.Nam chính Tả Dịch, cao phú soái, kim cương vương lão ngũ, anh tuấn tiêu sái phong độ bất phàm mà gần 30 vẫn không có bạn gái. Ngày đi làm anh là một đóa cao lãnh chi hoa, lạnh lùng  hung hăng khó tính với nữ giới, nhân viên; đêm về rúc ở nhà, đến nỗi không một cô gái nào dám theo đuổi.', '10', 11.1, 'https://diendanlequydon.com/downloads/image_prv/102/101929.jpg', 'Bệnh không thể yêu', 2000, 'NXB Kim Đồng', 100, '2020-09-01', 0, 20, 'Nguyễn Văn Nghĩa', 4),
(8, 'C Wright Mills', 'MS008', 'Giới tinh hoa quyền lực (tên tiếng anh: The Power Elite) xuất bản lần đầu vào năm 1956, thời điểm mà như Mills gọi, khi người Mỹ sống trong “một sự bùng nổ vật chất, một sự ca tụng chủ nghĩa dân tộc, một khoảng trống chính trị”. Dễ hiểu vì sao người Mỹ lại luôn tự mãn như Mills cáo buộc. Đây là cuốn sách quan trọng nhất trong ba cuốn Mills viết về xã hội Mỹ, cùng với The New Men of Power (Con người Quyền lực Mới, 1948) và White Collar (Giới Cổ cồn, 1951).', '10', 11.1, 'https://bizweb.dktcdn.net/100/180/408/products/gioi-tinh-hoa-quyen-luc-2.jpg?v=1606573615897', 'Tinh hoa quyền lự', 2000, 'NXB Alpha Books', 100, '2022-03-01', 0, 20, 'Nguyễn Sỹ', 4),
(9, 'Paulo Coelho', 'MS009', 'Thực hư về chuyện xuất bản nhiều như những cuốn sách kinh thánh rất có thể chỉ là một chiêu trò của các nhà Marketing. Tuy nhiên không thể phủ nhận rằng, Nhà giả kim (tiếng anh là The Alchemist) là một cuốn sách đã vượt tầm thời đại và có sức cuốn hút rất riêng mà hiếm tác phẩm đương thời nào sánh được. Bởi vậy nên không ngạc nhiên khi tác phẩm này đã trở thành một trong những cuốn sách “best-seller” liên tục trong nhiều năm tại các trang bán sách online.', '10', 10.1, 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg', 'Nhà giả kim', 2000, 'NXB Hội Nhà Văn', 100, '2020-01-01', 0, 30, 'Nguyễn Ba', 1),
(10, 'Giáo sư Cao Chi', 'MS010', 'Cuốn sách Vũ trụ đột sinh đề cập tới hầu hết các vấn đề thời sự của Vật lý hiện đại, được trình bày nhất quán như một cuốn sách hoàn chỉnh nhưng cũng có thể coi nó như một cuốn từ điển mà bạn có thể tra cứu gần như bất cứ vấn đề gì của Vật lý hiện đại mà bạn cảm thấy khúc mắc khi đọc những tài liệu khác.', '10', 10.1, 'http://static.nhanam.com.vn/thumb/0x230/crop/Books/Images/2022/10/11/BCHACUQQ.jpg', 'Vũ trụ đột sinh', 2000, 'NXB Kim Đồng', 100, '2020-01-01', 0, 30, 'Giáo sư Cao Chi', 1),
(11, 'Khuyết Danh', 'MS011', 'Mông Cổ bí sử là tác phẩm văn học viết đầu tiên của người Mông Cổ. Đây cũng là một tác phẩm sử học, ghi chép quá trình hình thành và phát triển của các bộ tộc trên thảo nguyên, từ giai đoạn khởi thủy cho đến năm thứ mười hai đời Nguyên Thái Tông Oa Khoát Đài (1240). ', '10', 10.1, 'https://bizweb.dktcdn.net/100/180/408/products/mong-co-bi-su-01.jpg?v=1613816846770', 'Mông Cổ bí sử', 148000, 'NXB Văn Học', 100, '2020-01-01', 0, 30, 'Khuyết Danh', 2),
(12, 'Laurence Bergreen', 'MS012', 'Hiện nay Marco Polo được nhiều người coi là một trong những du hành gia vĩ đại nhất, mặc dầu rằng những người thời ông chỉ coi ông như một người biết kể chuyện dí dỏm tài tình, còn những câu chuyện của ông là những chuyện hoang đường, viễn tưởng. Cũng cần lưu ý rằng, một số đoạn trong những câu chuyện của ông và cùng với sự hiện diện của ông tại triều đình Trung Quốc đều không được nhắc tới trong sử sách Trung Hoa. Cũng vì thế mà nhiều người đã tỏ ý nghi ngờ về tính trung thực cho những chuyến du hành của ông. ', '10', 10.1, 'http://bizweb.dktcdn.net/thumb/grande/100/180/408/products/marco-polo-tu-venice-toi-thuong-do.jpg?v=1614805129913', 'Marco polo', 227000, 'NXB Thế Giới', 100, '2020-01-01', 0, 30, 'Laurence Bergreen', 2),
(13, 'Cao Nguyên', 'MS013', 'Yêu là thế giống như một cuốn tự truyện, một cuốn nhật ký miêu tả rất sinh động cuộc đời 10 năm của tác giả, từ cô nữ sinh mập mạp, ngốc nghếch, ngây thơ phấn đấu trở thành sinh viên đại học nổi tiếng, thầm thương trộm nhớ một chàng trai cùng trường thông minh, giỏi giang kém mình 2 tuổi.', '10', 11.1, 'https://downloadsach.com/wp-content/uploads/2018/01/sach-yeu-la-the.jpg', 'Yêu là thế', 199000, 'NXB Văn Học', 100, '2018-09-01', 0, 20, 'Cao Nguyên', 1),
(14, 'Chandra Ghosh Ippen', 'MS014', 'You weren’t with me: 87% đánh giá 5 sao trên Amazon Cuốn sách này là một kho báu, rất phù hợp với đời sống nội tâm của trẻ nhỏ và mọi người ở mọi lứa tuổi khi chúng vật lộn với nỗi đau chung của sự chia ly với những người chúng yêu thương. Đây là một nguồn tài nguyên vô giá cho các bậc cha mẹ, người chăm sóc thay thế, bác sĩ lâm sàng và tất cả những người nỗ lực giúp trẻ nhỏ cảm thấy được lắng nghe, thấu hiểu và hỗ trợ.” - Alicia F. Lieberman, Ph.D. Irving B. Harris Giáo sư Khoa Tâm thần UCSF, tác giả nhiều cuốn sách nổi tiếng về trẻ em và gia đình', '30', 20.0, 'http://static.nhanam.com.vn/thumb/0x320/crop/Books/Images/2022/7/5/Q7DKCVUQ.jpg', 'Bố đã từng xa con', 30000, 'NXB Dân Trí', 100, '2022-07-11', 0, 20, 'Minh Thành', 3),
(15, 'Studio Afra', 'MS015', 'Khi con còn nằm trong nôi, bố mẹ chăm bẵm từng bữa sữa và giấc ngủ, chỉ mong con tự đứng tự đi được. Đến khi con đứng dậy, bắt đầu làm được việc này việc khác thì bố mẹ lại có nỗi lo khác. Làm sao để con không va vấp, làm sao con hiểu chuyện, giỏi giang, khôn lớn mỗi ngày?Bộ sách này là cẩm nang để bố mẹ đi cùng con qua tuổi mẫu giáo, giúp con tự lập dần trong cuộc sống. Nào tự tắm rửa, rồi ăn đủ chất, giữ an toàn khi đi đường, tập cảm ơn và xin lỗi... các kỹ năng nho nhỏ sẽ giúp bé tự lập dần.', '30', 20.0, 'http://static.nhanam.com.vn/thumb/0x320/crop/Books/Images/2022/4/7/L3E3CEKC.jpg', 'Mình từng ngủ ngon', 40000, 'NXB Dân Trí', 100, '2022-04-11', 0, 20, 'Khánh Nguyên', 3),
(16, 'Studio Afra', 'MS016', 'Những triển vọng đầy hứa hẹn của công nghệ sẽ được đưa ra bàn luận bên cạnh những hiểm họa như “đứt gãy” do công nghệ gây ra, việc kiểm soát thế giới bên trong dẫn tới sự sụp đổ của hệ thần kinh hay “tự do trong khuôn khổ”. Chính trị và tôn giáo có còn bắt tay nhau như trong quá khứ hay sẽ thao túng con người theo những cách riêng rẽ, mới mẻ hơn? Và những vấn đề toàn cầu ấy liên quan mật thiết tới hành vi và đạo đức của từng cá nhân riêng lẻ như thế nào? Xét cho cùng, những thách thức lớn nhất và những lựa chọn quan trọng nhất của ngày nay là gì? Ta cần chú ý đến điều gì? Ta nên dạy con cái ta những gì?', '30', 20.0, 'http://static.nhanam.com.vn/thumb/0x320/crop/Books/Images/2019/10/1/1TN5N61N.jpg', '21 bài học cho thế kỷ 21', 22000, 'NXB Thế Giới', 100, '2021-02-09', 0, 20, 'Dương Ngọc Trà', 4);

INSERT INTO `app_role`  VALUES 
(1, 'ROLE_ADMIN',0),
(2, 'ROLE_USER',0);
INSERT INTO `app_user`  VALUES 
(1, '2022-01-01', 'hoa@gmail.com', '$2a$10$AFDDl9JoG6mniECGmKvR3eg1YWyWPppzWweLeZ1doD2Wg3jJq3ukG',0, 'admin'),
(2, '2022-02-02', 'linh@gmail.com', '$2a$10$AFDDl9JoG6mniECGmKvR3eg1YWyWPppzWweLeZ1doD2Wg3jJq3ukG',0, 'user'),
(3, '2022-02-02', 'long@gmail.com', '$2a$10$AFDDl9JoG6mniECGmKvR3eg1YWyWPppzWweLeZ1doD2Wg3jJq3ukG',0, 'long'),
(4, '2022-02-02', 'dotronghoang95@gmail.com', '$2a$10$AFDDl9JoG6mniECGmKvR3eg1YWyWPppzWweLeZ1doD2Wg3jJq3ukG',0, 'hoang');
insert into `user_role` values
(1, 0, 1, 1),
(2, 0, 2, 1),
(3, 0, 2, 2),
(4, 0, 2, 3),
(5, 0, 2, 4);

insert into `customer` values
(1, 'Quảng Nam', '1995-01-08','hoa@gmail.com', '1', 'Lưu Hòa', 0976482451, 0, 1),
(2, 'Đà Nẵng', '1995-10-11','linh@gmail.com', '2', 'Nguyễn Văn Linh', 0901234785, 0, 2),
(3, 'Quảng Trị', '1999-10-10','long@gmail.com', '2', 'Nguyễn Thành Long', 090101010, 0, 3),
(4, 'Huế', '1995-10-11','dotronghoang95@gmail.com', '2', 'Trần Văn Hoàng', 0901020304, 0, 4);





-- insert into `roles` values (1, 'ROLE_ADMIN', 0), (2, 'ROLE_USER', 0);
-- INSERT INTO `book_store`.`app_role` VALUES ('1', 'ROLE_NAME',0),(2, 'ROLE_USER', 0);


